### PR TITLE
Fully resolve names when generating bindings

### PR DESCRIPTION
**Pull request by miniBill**

### CODE REVIEW

**Comment by peteygao** [comment]
I can confirm that this PR fixes an issue that I ran into using [elm-generic-dict](https://package.elm-lang.org/packages/miniBill/elm-generic-dict/latest/). 

Let's say I have a type in the file `Bridge.elm`:
```elm
type Email =
    Email String


emailToString : Email -> String
emailToString (Email email) =
    email
```

Meant to be used as a tagged value, so I create `Generated.elm` as such:
```elm
main : Program {} () ()
main =
    Generate.run 
        [ emailDictFile ]


emailDictFile : Elm.File
emailDictFile =
    GenericDict.init
        { keyType = Gen.Bridge.annotation_.email
        , namespace = []
        , toComparable = Gen.Bridge.emailToString
        }
        |> GenericDict.withTypeName "EmailDict"
        |> GenericDict.generateFile
```

Executing `elm-codegen run` throws this error/warning in the terminal:
```bash
--ELM CODEGEN WARNING-----------------------------------------------------------
In the generated file: EmailDict.elm

    When trying to figure out the type for member, I ran into an issue
    
    I found
    
        Email
    
    But I was expecting:
    
        Bridge.Email
    
    I'm not as smart as the Elm compiler :/, but we're good friends.  I especially get confused when there are a lot of type aliases.
    If you need to, try using Elm.withType to tell me what the type should be!
```

And the resulting file is this mangled thing (which I can manually fix by replacing the types where the error messages are printed):
```elm
import Bridge
import Dict


type EmailDict 

I found

  was expecting:

 v
    = EmailDict
        (Dict.Dict (Err: 

I found

    Email

But I was expecting:

    Bridge.Email) ( Bridge.Email, v ))

{-... rest of the file is well-formed ...-}
```

The manually fixed file looks like this, and it works fine:
```elm
import Bridge
import Dict


type EmailDict v
    = EmailDict (Dict.Dict String ( Bridge.Email, v ))
```

This PR fixes it so that there's no mangled output in the resulting generated file, and that it properly resolves it as the base type `String` instead of `Bridge.Email` which is incorrect.

**Comment by mdgriffith** [comment]
Thank you both!  Just published 4.4.1 on elm package.  Thank you for both the work and the verification, that's a huge load of my brain 🙏

**Comment by peteygao** [comment]
@mdgriffith Thanks for publishing a new version! Minor issue with the new release: `elm-codegen --version` version `0.5.1` still reports itself as `0.5.0` since the CLI's version number is hardcoded in [cli/bin.ts](https://github.com/mdgriffith/elm-codegen/blob/c4b230bb4e26d3b620b067b7a8febeadd7da9a24/cli/bin.ts#L16). This threw me for a loop initially after I updated the package using `npm` and checked to make sure I had the latest version, and still saw `0.5.0` 😅

**Comment by mdgriffith** [comment]
@peteygao lol, oh no, lemme take a look

**Comment by mdgriffith** [comment]
Just published `0.5.2` with the only change being that `--version` reads as `0.5.2` 😹

**Pull request merged**
